import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { toast } from '@/components/ui/use-toast';
import { Tables } from '@/integrations/supabase/types';

type SocialLink = Tables<'social_links'>;

const socialMediaPlatforms = ['facebook', 'instagram', 'x', 'tiktok'];

export default function SocialLinksSettings() {
  const [socialLinks, setSocialLinks] = useState<SocialLink[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchSocialLinks = async () => {
      setLoading(true);
      const { data, error } = await supabase
        .from('social_links')
        .select('*')
        .in('name', socialMediaPlatforms)
        .order('name');

      if (error) {
        toast({
          title: 'Erreur',
          description: "Impossible de charger les liens des réseaux sociaux.",
          variant: 'destructive',
        });
        console.error(error);
      } else {
        // Ensure all platforms are present, even if they have no URL yet
        const existingLinks = data || [];
        const allLinks = socialMediaPlatforms.map(platform => {
          const existing = existingLinks.find(link => link.name === platform);
          return existing || { id: Date.now() + Math.random(), name: platform, url: '', created_at: new Date().toISOString() };
        });
        setSocialLinks(allLinks);
      }
      setLoading(false);
    };

    fetchSocialLinks();
  }, []);

  const handleInputChange = (id: number, value: string) => {
    setSocialLinks(prevLinks =>
      prevLinks.map(link => (link.id === id ? { ...link, url: value } : link))
    );
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    const upsertPromises = socialLinks.map(link => {
        // The table has a UNIQUE constraint on `name`, so we upsert on `name`.
        // The autogenerated `id` is not stable for new entries.
        return supabase.from('social_links').upsert({
            name: link.name,
            url: link.url || null,
        }, { onConflict: 'name' });
    });

    const results = await Promise.all(upsertPromises);

    const hasError = results.some(res => res.error);

    if (hasError) {
      toast({
        title: 'Erreur',
        description: "Une erreur est survenue lors de la mise à jour des liens.",
        variant: 'destructive',
      });
      results.forEach(res => {
        if (res.error) console.error('Error updating social link:', res.error);
      });
    } else {
      toast({
        title: 'Succès',
        description: 'Les liens des réseaux sociaux ont été mis à jour.',
      });
    }
    setLoading(false);
  };

  if (loading && !socialLinks.length) {
    return <div>Chargement...</div>;
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {socialLinks.map(link => (
        <div key={link.id} className="space-y-2">
          <Label htmlFor={link.name} className="capitalize">{link.name}</Label>
          <Input
            id={link.name}
            type="url"
            value={link.url || ''}
            onChange={e => handleInputChange(link.id, e.target.value)}
            placeholder={`https://www.${link.name}.com/votre-page`}
          />
        </div>
      ))}
      <Button type="submit" disabled={loading}>
        {loading ? 'Enregistrement...' : 'Enregistrer les modifications'}
      </Button>
    </form>
  );
}