CREATE TABLE fcm_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE fcm_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON fcm_tokens FOR SELECT USING (true);
CREATE POLICY "Allow individual insert" ON fcm_tokens FOR INSERT WITH CHECK (true);