// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxipmsunesxtkepjwxvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4aXBtc3VuZXN4dGtlcGp3eHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTQ5MjksImV4cCI6MjA3MjE3MDkyOX0.6l38lZWoeZ-PlzBw9UghpBTOgglB71kRa6_Tov35gvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});